/**
 * Generates lib/rarity.ts — the lookup table behind the "1 in N" figure.
 *
 * The product's whole claim is that it finds something *unique* as well as
 * valuable, and until now the page only ever argued the second half. Rarity
 * can't be computed in closed form from the scoring, so it is sampled here at
 * build time and baked in as a table rather than simulated in the browser.
 *
 * What the number means, precisely: how often a given (archetype + two
 * strongest signals) combination comes out of this instrument when its
 * questions are answered at random. It is a property of the profile space the
 * questions can produce — NOT an observed frequency among real people, which
 * we could only know by collecting answers, which we deliberately don't. The
 * copy on the reveal has to keep saying so.
 *
 * Re-run with `npm run build:rarity` whenever the question bank, the option
 * vectors or the archetype vectors change. If it isn't re-run, unknown keys
 * simply return null and the section hides itself rather than lying.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { CORE_QUESTIONS, DEEP_QUESTIONS, QUESTIONS } from "../lib/questions";
import { buildResult, emptyAnswers, type Answers } from "../lib/scoring";
import { STAGE_KEYS } from "../lib/stages";

const SAMPLES = 300_000;
const rnd = (n: number) => Math.floor(Math.random() * n);
const full = [...CORE_QUESTIONS, ...DEEP_QUESTIONS];

function randomAnswers(deck: typeof QUESTIONS): Answers {
  const a = emptyAnswers();
  a.stage = STAGE_KEYS[rnd(STAGE_KEYS.length)];
  for (const q of deck) {
    if (q.kind === "text") continue;
    if (q.kind === "multi") {
      const pool = [...q.options];
      const take = 1 + rnd(q.maxPicks);
      const picks: string[] = [];
      for (let k = 0; k < take && pool.length; k++) {
        picks.push(pool.splice(rnd(pool.length), 1)[0].id);
      }
      a.choices[q.id] = picks;
    } else {
      a.choices[q.id] = [q.options[rnd(q.options.length)].id];
    }
  }
  return a;
}

const counts = new Map<string, number>();
for (let i = 0; i < SAMPLES; i++) {
  // Both paths exist in the wild, so sample both.
  const r = buildResult(randomAnswers(i % 2 ? full : CORE_QUESTIONS));
  const key = `${r.archetype.id}|${r.readings.slice(0, 2).map((x) => x.key).join("+")}`;
  counts.set(key, (counts.get(key) ?? 0) + 1);
}

const sorted = [...counts.entries()].sort((a, b) => b[1] - a[1]);
const body = sorted.map(([k, v]) => `  ${JSON.stringify(k)}: ${v},`).join("\n");

const out = `// GENERATED by scripts/build-rarity.ts — do not edit by hand.
// Re-run \`npm run build:rarity\` after changing questions or archetypes.
//
// Sampled frequency of each (archetype + top-two-signals) profile across
// ${SAMPLES.toLocaleString("en-GB")} randomly answered runs. This describes the space of
// profiles the instrument can produce, not a population of real people — see
// the header of the generator for why that distinction has to survive into
// the copy.

export const RARITY_SAMPLES = ${SAMPLES};
export const RARITY_COMBINATIONS = ${sorted.length};

export const RARITY: Record<string, number> = {
${body}
};
`;

// __dirname is the compiled location under .scripts-dist; npm runs scripts
// from the package root, so resolve the real source tree from cwd.
const target = join(process.cwd(), "lib", "rarity.ts");
writeFileSync(target, out, "utf8");
console.log(`wrote lib/rarity.ts — ${sorted.length} combinations from ${SAMPLES} samples`);
console.log(`rarest 1 in ${Math.round(SAMPLES / sorted[sorted.length - 1][1])}, most common 1 in ${Math.round(SAMPLES / sorted[0][1])}`);
